# training:
epochs: 1001
batch_size: 2048
learning_rate: 0.0001 #1e-4
weight_decay: 0.00001 #1e-5
# transform:
use_stft: false
delay: 8
embedding: 8
# model:
handler: models.ImagenFew.handler
img_resolution: 8
unet_channels: 32
ch_mult: [1,2,2,4]
attn_resolution: [8,4,2]
diffusion_steps: 36
ema: true
ema_warmup: 100
# logging:
logging_iter: 100
tags: []
run_dir: ImagenFew/Rainfall/
# Data
datasets_dir: ./data/
seq_len: 24
pretrain: false
datasets:
  - name: Rainfall
    data: custom
    embed: timeF
    rel_path: rainfall/train/rainfall_10min.csv
    features: S
    target: avg_rainfall
    freq: 10min
    label_len: 0
    pred_len: 0
train_on_datasets:
  - Rainfall
